version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - "POSTGRES_PASSWORD=1234"
    ports:
      - "5432:5432"
      
